# Git Aliases
alias gs="git status"
alias ga="git add"
alias gc="git commit -m"
alias gd="git diff"
alias gm="git merge"
alias gpl="git pull"
alias gps="git push"
alias gl="git log"
alias gk="git checkout"
alias gb="git branch"
alias gr="git remote"
alias gf="git fetch"
